spring.application.name=API-Gateway

server.port=8080
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# routes to user service (lb:// enables load balancing)

spring.cloud.gateway.routes[0].id=file-service
spring.cloud.gateway.routes[0].uri=lb://FILE-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/files/**

spring.cloud.gateway.routes[1].id=folder-service
spring.cloud.gateway.routes[1].uri=lb://FOLDER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/folders/**

spring.cloud.gateway.routes[2].id=search-service
spring.cloud.gateway.routes[2].uri=lb://SEARCH-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/search/**

# update all value