spring.application.name=Search-Service

server.port=8085

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# ------------ Actuator ------------
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

logging.level.org.springframework.web=DEBUG

# ------------ CIRCUIT BREAKER ------------
resilience4j.circuitbreaker.instances.File-Service.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.File-Service.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.File-Service.wait-duration-in-open-state=10000
resilience4j.circuitbreaker.instances.File-Service.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.File-Service.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.File-Service.record-exceptions[0]=java.io.IOException
resilience4j.circuitbreaker.instances.File-Service.record-exceptions[1]=java.util.concurrent.TimeoutException

spring.cloud.openfeign.circuitbreaker.enabled=true


