spring.application.name=File-Service

server.port=8081

# H2 Database Config
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=root

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA Config (if using Hibernate)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# actuatar
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
